In [19]:
import pandas as pd
import numpy as np

import os
import re

In [3]:
working_dir = '/home/rgiordan/Documents/git_repos/Presentations/CCC_covid_vote'

In [7]:
responses = pd.read_csv(os.path.join(working_dir, 'example.csv'))

In [112]:
# Select the columns that compile the votes

#print(responses.columns)
a_col = responses.columns[3]
b_col = responses.columns[4]
c_col = responses.columns[5]
d_col = responses.columns[6]
# print('\n'.join([a_col, b_col, c_col, d_col]))

# Assert that I have selected the columns correctly
assert(re.search("Policy A", a_col))
assert(re.search("Policy B", b_col))
assert(re.search("Policy C", c_col))
assert(re.search("Policy D", d_col))

In [129]:
def ConvertToNumericVote(pd_col):
    # Empty rows (not voted on) are storted as nan, not strings.
    vote_str = pd_col.fillna('0').to_numpy()
    
    # Keep only the numbers.
    vote_str = np.array([ re.sub(r'[^0-9]', '', v) for v in vote_str ])
    
    return vote_str.astype('int')

votes = np.vstack([
    ConvertToNumericVote(responses[col]) for col in [ a_col, b_col, c_col, d_col ]
])
print(votes)

# Assert that the A vote is the first row as expected.
assert(np.all(ConvertToNumericVote(responses[a_col]) == votes[0, :]))

[[2 4 4 4 0 4 3 4 4 4 4 2 4 4 3 2 4 3 2]
 [3 3 3 3 0 2 4 3 3 2 1 1 3 2 4 1 3 4 3]
 [1 2 2 2 2 1 2 2 2 3 2 3 2 3 3 3 2 2 1]
 [4 1 1 1 1 3 1 1 1 1 3 4 1 1 1 4 1 1 4]]


In [152]:
def FindWinner(votes):
    num_voters = votes.shape[1]
    num_votes = np.sum(votes == 1)
    assert(num_votes <= num_voters)
    if num_votes != num_voters:
        print('Some did not vote. ', num_votes, num_voters)
    vote_count = np.sum(votes == 1, axis=1)
    majority = vote_count / num_votes > 0.5
    if np.any(majority):
        return np.argwhere(majority)[0][0]
    else:
        print('No majority')
        return -1
    
FindWinner(votes)

3